#Chapter 1 토큰화

In [1]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [2]:
import warnings
warnings.simplefilter('ignore')

In [3]:
from nltk.tokenize import sent_tokenize

In [4]:
#문제1. 토큰화 패키지를 사용하여 토큰화를 해봅시다.
#문제 1-1.
sentence = 'One of the essential things in the life of a human being is communication. We need to communicate with other human beings to deliver information, express our emotions, present ideas, and much more. The key to communication is language. '
token1 = sent_tokenize(sentence)
token1

['One of the essential things in the life of a human being is communication.',
 'We need to communicate with other human beings to deliver information, express our emotions, present ideas, and much more.',
 'The key to communication is language.']

In [5]:
from nltk.tokenize import word_tokenize
from nltk.tokenize import WordPunctTokenizer
from tensorflow.keras.preprocessing.text import text_to_word_sequence

In [6]:
#문제 1-2.
sentence1 ='We need to communicate with other human beings to deliver information, express our emotions, present ideas, and much more.'
sentence2 ='The price\t of burger \nin BurgerKing is Rs.36.\n'
word_token1 = word_tokenize(sentence1)
word_token2 = word_tokenize(sentence2)

In [7]:
print(word_token1)
print(word_token2)
#word_tokenize는 Rs.36을 하나의 단어로 분류함.
#이스케이프 문자 \t는 탭이고 \n은 줄바꿈인데 따로 처리를 하지는 않고 무시되었음.

['We', 'need', 'to', 'communicate', 'with', 'other', 'human', 'beings', 'to', 'deliver', 'information', ',', 'express', 'our', 'emotions', ',', 'present', 'ideas', ',', 'and', 'much', 'more', '.']
['The', 'price', 'of', 'burger', 'in', 'BurgerKing', 'is', 'Rs.36', '.']


In [8]:
wordp_token1 = WordPunctTokenizer().tokenize(sentence1)
wordp_token2 = WordPunctTokenizer().tokenize(sentence2)

In [9]:
print(wordp_token1)
print(wordp_token2)

['We', 'need', 'to', 'communicate', 'with', 'other', 'human', 'beings', 'to', 'deliver', 'information', ',', 'express', 'our', 'emotions', ',', 'present', 'ideas', ',', 'and', 'much', 'more', '.']
['The', 'price', 'of', 'burger', 'in', 'BurgerKing', 'is', 'Rs', '.', '36', '.']


In [10]:
text_word_token1=text_to_word_sequence(sentence1)
text_word_token2=text_to_word_sequence(sentence2)
#WordPunctTokenizer는 .(구두점)을 별도로 분류하는 것을 볼 수 있음.
#이스케이프 문자 \t는 탭이고 \n은 줄바꿈인데 따로 처리를 하지는 않고 무시되었음.

In [11]:
print(text_word_token1)
print(text_word_token2)
#text_to_word_sequnce는 모든 알파벳이 소문자로 변경된것을 확인할 수 있음.
#이스케이프 문자 \t는 탭이고 \n은 줄바꿈인데 따로 처리를 하지는 않고 무시되었음.
#마침표나 컴마등의 구두점도 모두 제거되어있음. 

['we', 'need', 'to', 'communicate', 'with', 'other', 'human', 'beings', 'to', 'deliver', 'information', 'express', 'our', 'emotions', 'present', 'ideas', 'and', 'much', 'more']
['the', 'price', 'of', 'burger', 'in', 'burgerking', 'is', 'rs', '36']


In [12]:
!pip install konlpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 20.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 465.3/465.3 kB 47.0 MB/s eta 0:00:00


In [13]:
#문제 1-3.
import konlpy
import pandas as pd
from konlpy.tag import *

okt = Okt()

In [18]:
k_table = pd.read_table('/content/drive/MyDrive/통계학과/피셋/주분/2주차/1-3.txt')
k_table

id                                           document  label
0        9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1        3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2       10265843                                  너무재밓었다그래서보는것을추천한다      0
3        9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4        6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1
...          ...                                                ...    ...
149995   6222902                                인간이 문제지.. 소는 뭔죄인가..      0
149996   8549745                                      평점이 너무 낮아서...      1
149997   9311800                    이게 뭐요? 한국인은 거들먹거리고 필리핀 혼혈은 착하다?      0
149998   2376369                        청춘 영화의 최고봉.방황과 우울했던 날들의 자화상      1
149999   9619869                           한국 영화 최초로 수간하는 내용이 담긴 영화      0

[150000 rows x 3 columns]

In [19]:
k_sentences = k_table['document'][:50]

In [20]:
okt_list=[]
for k_sentence in k_sentences:
  clean_list = []
  mal = okt.pos(k_sentence,norm=True,stem=True)
  # 조사, 어미, 문장 부호 제외
  for word in mal:
    if word[1] not in ['Josa','Eomi','Punctuation']:
      clean_list.append(word)
  okt_list.append(clean_list)

for sent in okt_list:
  print(sent)

[('아', 'Exclamation'), ('더빙', 'Noun'), ('진짜', 'Noun'), ('짜증나다', 'Adjective'), ('목소리', 'Noun')]
[('흠', 'Noun'), ('포스터', 'Noun'), ('보고', 'Noun'), ('초딩', 'Noun'), ('영화', 'Noun'), ('줄', 'Noun'), ('오버', 'Noun'), ('연기', 'Noun'), ('가볍다', 'Adjective'), ('않다', 'Verb')]
[('너', 'Modifier'), ('무재', 'Noun'), ('밓었', 'Noun'), ('다그', 'Noun'), ('래서', 'Noun'), ('보다', 'Verb'), ('추천', 'Noun'), ('다', 'Adverb')]
[('교도소', 'Noun'), ('이야기', 'Noun'), ('구먼', 'Noun'), ('솔직하다', 'Adjective'), ('재미', 'Noun'), ('없다', 'Adjective'), ('평점', 'Noun'), ('조정', 'Noun')]
[('사이', 'Modifier'), ('몬페', 'Noun'), ('그', 'Determiner'), ('의', 'Noun'), ('익살스럽다', 'Adjective'), ('연기', 'Noun'), ('돋보이다', 'Verb'), ('영화', 'Noun'), ('스파이더맨', 'Noun'), ('늙다', 'Verb'), ('보이다', 'Verb'), ('하다', 'Verb'), ('커스틴', 'Noun'), ('던스트', 'Noun'), ('너무나도', 'Adverb'), ('이쁘다', 'Adjective'), ('보이다', 'Verb')]
[('막', 'Noun'), ('걸음', 'Noun'), ('마', 'Noun'), ('떼다', 'Verb'), ('3', 'Number'), ('세', 'Noun'), ('초등학교', 'Noun'), ('1', 'Number'), ('학년', 'Noun'), ('생인', 'N

In [21]:
#문제2
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [22]:
#불용어 사전 설정
eliminate_words = set(stopwords.words('english'))
sentence = 'We need a common language to communicate, which both ends of the conversation can understand.'
word_tokens = word_tokenize(sentence)

res = []
for word in word_tokens:
  if word not in eliminate_words:
    res.append(word)

print('불용어 제거 전 : ',word_tokens)
print('불용어 제거 후 : ',res)

불용어 제거 전 :  ['We', 'need', 'a', 'common', 'language', 'to', 'communicate', ',', 'which', 'both', 'ends', 'of', 'the', 'conversation', 'can', 'understand', '.']
불용어 제거 후 :  ['We', 'need', 'common', 'language', 'communicate', ',', 'ends', 'conversation', 'understand', '.']


In [ ]:
#문제3 어간추출
from nltk.stem import PorterStemmer

In [ ]:
pts = PorterStemmer()
word_list = ['dies','going','watched','has','are','went','wanted','visiting','invites','deserved','This','was','names',
             'chest','heights','crosses','Bones','found','looking','forward','back','on','ground']
print('원본 : ',word_list)
print('어간 추출 후 : ',[pts.stem(word) for word in word_list])

In [ ]:
#문제3 표제어추출
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

In [ ]:
wnl = WordNetLemmatizer()
word_list = ['dies','going','watched','has','are','went','wanted','visiting','invites','deserved','This','was','names',
             'chest','heights','crosses','Bones','found','looking','forward','back','on','ground']
print('원본 : ',word_list)
print('어간 추출 후 : ',[wnl.lemmatize(word) for word in word_list])

In [ ]:
#품사 정보 추가
print(wnl.lemmatize('dies','v'))
print(wnl.lemmatize('watched','v'))
print(wnl.lemmatize('has','v'))

#Chapter 2 임베딩

In [82]:
from sklearn.feature_extraction.text import CountVectorizer

In [83]:
#문제1
corpus = [
    'This is the first document.',
    'This is the second second document.',
    'And the third one.',
    'Is this the first document?',
    'The last document?'
]
vector=CountVectorizer(stop_words=['the','is','and'])
print(vector.fit_transform(corpus).toarray())
print(vector.vocabulary_)

[[1 1 0 0 0 0 1]
 [1 0 0 0 2 0 1]
 [0 0 0 1 0 1 0]
 [1 1 0 0 0 0 1]
 [1 0 1 0 0 0 0]]
{'this': 6, 'first': 1, 'document': 0, 'second': 4, 'third': 5, 'one': 3, 'last': 2}


In [84]:
#문제2
from gensim.models import Word2Vec

In [88]:
#문제 2-1,2-2,2-3
sentences = []
with open('/content/drive/MyDrive/통계학과/피셋/주분/2주차/2-1.txt') as f:
    for line in f.readlines():
        text_word_token=text_to_word_sequence(line)
        sentences.append(text_word_token)

In [89]:
#sg=0 CBOW
model = Word2Vec(sentences,window=5,vector_size=100,min_count=1,sg=0)
#문제 2-4 유사도 출력
print(model.wv.similarity('peter','wendy'))
print(model.wv.similarity('peter','hook'))

-0.15217832
0.014551653


In [90]:
#sg=1 skip_gram
model = Word2Vec(sentences,window=5,vector_size=100,min_count=1,sg=1)
#문제 2-4 유사도 출력
print(model.wv.similarity('peter','wendy'))
print(model.wv.similarity('peter','hook'))

0.37445843
0.51672363


In [91]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 94.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 92.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 kB 31.4 MB/s eta 0:00:00


In [92]:
#문제3
from transformers import BertModel
from transformers import BertTokenizer
import torch

In [93]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

In [94]:
#문제3-1
text = 'NLP is an interdisciplinary subfield of linguistics, computer science, and artificial intelligence'
tokens = tokenizer.encode_plus(text,return_attention_mask=True,return_token_type_ids=True)
tokens

{'input_ids': [101, 17953, 2361, 2003, 2019, 18593, 4942, 3790, 1997, 15397, 1010, 3274, 2671, 1010, 1998, 7976, 4454, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [108]:
#문제3-2
text='[CLS] NLP is an interdisciplinary subfield of linguistics, computer science, and artificial intelligence [SEP]'
#문제3-3
token = tokenizer(text)
#문제3-4
ids = tokenizer.convert_tokens_to_ids(token)
#문제3-5
attention_mask = tokenizer(text)['attention_mask']
#문제3-6
ids_tensor = torch.tensor(ids)
attention_tensor = torch.tensor(attention_mask)

In [109]:
model = BertModel.from_pretrained("bert-base-uncased",output_hidden_states=True)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [116]:
output=model()

TypeError: ignored

#Chapter 3 정형 데이터 적용(LSTM)

In [62]:
#문제1
df= pd.read_csv('/content/drive/MyDrive/통계학과/피셋/주분/2주차/Modelling.csv')

In [63]:
df.describe()

Open        High         Low       Close   Adj Close  \
count  253.000000  253.000000  253.000000  253.000000  253.000000   
mean    81.977273   82.973043   80.871462   81.998656   80.479205   
std      9.228221    8.946584    9.678252    9.272335    9.288642   
min     55.549999   57.439999   50.020000   56.330002   54.995056   
25%     75.370003   76.370003   74.430000   75.440002   74.068405   
50%     82.599998   83.239998   81.750000   82.410004   81.351830   
75%     88.500000   89.110001   87.720001   88.510002   86.475174   
max    103.510002  106.089996  102.750000  105.389999  104.527336   

             Volume  
count  2.530000e+02  
mean   9.687298e+06  
std    5.131906e+06  
min    1.847800e+06  
25%    6.197700e+06  
50%    8.238600e+06  
75%    1.137890e+07  
max    2.877060e+07

In [64]:
df.head(3)

Date       Open       High        Low      Close  Adj Close    Volume
0  2019-12-11  86.260002  86.870003  85.849998  86.589996  84.145752   4921900
1  2019-12-12  88.000000  88.889999  87.540001  88.209999  85.720032  10282100
2  2019-12-13  88.019997  88.790001  87.580002  88.669998  86.167046   6714100

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253 entries, 0 to 252
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Date       253 non-null    object 
 1   Open       253 non-null    float64
 2   High       253 non-null    float64
 3   Low        253 non-null    float64
 4   Close      253 non-null    float64
 5   Adj Close  253 non-null    float64
 6   Volume     253 non-null    int64  
dtypes: float64(5), int64(1), object(1)
memory usage: 14.0+ KB


In [66]:
#문제2
df['Date']=pd.to_datetime(df['Date'])
df.index = df['Date']
df = df.drop(['Date'],axis=1)

In [67]:
#문제3
df['Volume']=df['Volume'].astype(float)
y = df['Volume']
y=pd.DataFrame(y)
x = df.loc[:,(df.columns != 'Volume')]

In [68]:
#float으로 변경확인
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 253 entries, 2019-12-11 to 2020-12-10
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Open       253 non-null    float64
 1   High       253 non-null    float64
 2   Low        253 non-null    float64
 3   Close      253 non-null    float64
 4   Adj Close  253 non-null    float64
 5   Volume     253 non-null    float64
dtypes: float64(6)
memory usage: 13.8 KB


In [69]:
#x,y 컬럼 확인
print(x.columns)
print(y.columns)

Index(['Open', 'High', 'Low', 'Close', 'Adj Close'], dtype='object')
Index(['Volume'], dtype='object')


In [70]:
#문제4
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [71]:
#스케일링
ss = StandardScaler()
mm = MinMaxScaler()
x_scaled = ss.fit(x).transform(x)
y_scaled = mm.fit(y).transform(y)

In [72]:
#문제5
from sklearn.model_selection import train_test_split

In [73]:
x_train, x_test,y_train,y_test = train_test_split(x_scaled,y_scaled, test_size=53)

In [74]:
#분리 확인
print('x_train : ' ,x_train.shape)
print('y_train : ' ,y_train.shape)
print('x_test : ' ,x_test.shape)
print('y_test : ' ,y_test.shape)

x_train :  (200, 5)
y_train :  (200, 1)
x_test :  (53, 5)
y_test :  (53, 1)


In [75]:
#문제6
import torch
x_train = torch.tensor(x_train).reshape(200, 1, 5) #, dtype=torch.float32
x_test=torch.tensor(x_test).reshape(53,1,5)
y_train=torch.tensor(y_train)
y_test=torch.tensor(y_test)

In [76]:
#shape 확인
print('x_train : ' ,x_train.shape)
print('y_train : ' ,y_train.shape)
print('x_test : ' ,x_test.shape)
print('y_test : ' ,y_test.shape)

x_train :  torch.Size([200, 1, 5])
y_train :  torch.Size([200, 1])
x_test :  torch.Size([53, 1, 5])
y_test :  torch.Size([53, 1])


In [77]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [78]:
#문제7
import torch.nn as nn
class LSTMModel(nn.Module):
    def __init__(self, input_size, hidden_size, output_size, num_layers):
        super(LSTMModel, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers)
        self.fc = nn.Linear(hidden_size, output_size)
        
    def forward(self, input):
        batch_size = input.size(1) # batch_size와 sequence length의 순서를 변경합니다.
        h0 = torch.zeros(1, batch_size, self.hidden_size).to(device) # hidden state 크기를 변경합니다.
        c0 = torch.zeros(1, batch_size, self.hidden_size).to(device) # hidden state 크기를 변경합니다.
        output, (hn, cn) = self.lstm(input, (h0, c0))
        output = self.fc(output[-1])
        return output
        

In [80]:
#문제8, 문제9
input_size = 5
hidden_size = 2
output_size = 1
num_layers = 1
model = LSTMModel(input_size, hidden_size, output_size, num_layers).to(device)

# loss function, optimizer 설정
loss_fn = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.0001)

# 모델 학습
num_epochs = 5000
x_train = x_train.float().to(device)
y_train = y_train.float().to(device)
for epoch in range(num_epochs):
    optimizer.zero_grad()
    output = model(x_train)
    loss = loss_fn(output, y_train)
    loss.backward()
    optimizer.step()
    
    # 1000번마다 loss 출력
    if epoch % 1000 == 0:
        print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}")

Epoch [1/5000], Loss: 0.6479
Epoch [1001/5000], Loss: 0.3207
Epoch [2001/5000], Loss: 0.1348
Epoch [3001/5000], Loss: 0.0586
Epoch [4001/5000], Loss: 0.0419


In [81]:
output

tensor([[0.2926]], device='cuda:0', grad_fn=<AddmmBackward0>)